### ISSUE TITLE
Error trying to run tests after initial setup: Cannot find module

### ISSUE THREAD

**Issue by spanuska** [onfido/jasmine-react-rails#3]
I've gotten through all the setup, then ran `grunt` just for a sanity check, but this is what I got:

```
$  grunt
Running "wrap:advanced" (wrap) task
Wrapped 0 files
Running "react:dynamic_mappings" (react) task

Running "execute:target" (execute) task
-> executing myapp/react_spec/run_tests.js
module.js:341
    throw err;
    ^

Error: Cannot find module 'myapp/react_spec/support/compiled/components//modals/modal_ctrl'
    at Function.Module._resolveFilename (module.js:339:15)
    at internalRewire (myapp/react_spec/node_modules/rewire/lib/rewire.js:23:25)
    at rewire (myapp/react_spec/node_modules/rewire/lib/index.js:11:12)
    at Object.<anonymous> (myapp/react_spec/support/compiled/spec/modals/form_modal_ctrl_spec.js:6:27)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
Warning: -> error 1 myapp/react_spec/run_tests.js (780ms) Use --force to continue.

Aborted due to warnings.
```

Could this have anything to do with the path 'myapp/react_spec/support/compiled/components//modals/modal_ctrl' having 2 slashes between components and modals? Any idea how I can fix this? Thank you!!

**Comment by BlakeTurner** [comment]
Looks like you've got a double / in `myapp/react_spec/support/compiled/components//modals/modal_ctrl` before `modals`. Could you be prepending something with a slash that doesn't need to be there?

**Comment by spanuska** [comment]
Anything is possible! But I'm not sure how I would have done that. I've
only added 2 files related to testing. I've added:
- 1 component at
  myapp/app/assets/javascripts/components/my_component.js.jsx, and
- 1 test to myapp/app/react_spec/tests/my_component_spec.jsx

(BTW, thanks for building this AND for the speedy response to my issue!)

**Comment by BlakeTurner** [comment]
Hrm. I haven't run this code for a long time, so I have a feeling something may have changed in the way rewire handles paths.

Try changing 

``` javascript
var FormModalCtrlModule = rewire(__component_base + '/modals/modal_ctrl');
```

to

``` javascript
var FormModalCtrlModule = rewire(__component_base + 'modals/modal_ctrl');
```

in `tests/modals/form_modal_ctrl_spec.jsx`. Lemme know if that helps.

**Comment by spanuska** [comment]
That did take care of the double / issue. But the error now is otherwise the same. Still can't find `modal_ctrl`.

**Comment by BlakeTurner** [comment]
Ah, I know what happened! Those specs were meant to exist only as examples. The modules cant be found because they don't exist in your system. (Modules are compiled down from [rails root]/app/assets/javascripts/react_components to [jasmine-react-rails]/compiled/components/)

 Apologies. I will update the repo, leaving one commented-out file as an example. Delete the tests and it'll work fine.

**Comment by spanuska** [comment]
Thank you!

**Comment by BlakeTurner** [comment]
No prob! Dumb mistake on my part. Any other feedback is appreciated.
